Repository down-work-out-together/down, pull requests merged in 2024-02, with the labels that each got.

#27 update : #9 회원가입 정보 사용자 이름 추가
  backend/src/main/java/com/example/demo/domain/user/dto/command/UserJoinCommand.java
  backend/src/main/java/com/example/demo/domain/user/entity/UserEntity.java
  backend/src/main/java/com/example/demo/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/example/demo/domain/user/model/User.java
  backend/src/main/java/com/example/demo/global/auth/PrincipalDetails.java
  backend/src/main/java/com/example/demo/global/auth/oauth/OAuth2UserService.java
Labels: BackEnd

#52 feat: #49 사용자 정보 성별, 생년월일 추가
  backend/build.gradle
  backend/src/main/java/com/example/demo/domain/chat/dto/ChatRoomDto.java
  backend/src/main/java/com/example/demo/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/example/demo/domain/chat/entity/ChatRoom.java
  backend/src/main/java/com/example/demo/domain/user/dto/command/UserJoinCommand.java
  backend/src/main/java/com/example/demo/domain/user/entity/UserEntity.java
  backend/src/main/java/com/example/demo/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/example/demo/domain/user/model/User.java
  backend/src/main/java/com/example/demo/domain/user/repository/UserRepository.java
  backend/src/main/java/com/example/demo/domain/user/service/UserService.java
  backend/src/main/java/com/example/demo/global/auth/kakao/KaKaoAccessTokenResponse.java
  backend/src/main/java/com/example/demo/global/auth/kakao/KaKaoOAuth2Controller.java
  backend/src/main/java/com/example/demo/global/auth/kakao/KakaoOAuth2Service.java
  backend/src/main/java/com/example/demo/global/auth/kakao/KakaoUserInfo.java
  backend/src/main/java/com/example/demo/global/auth/oauth/OAuth2UserService.java
  backend/src/main/java/com/example/demo/global/exception/ExceptionCode.java
  backend/src/main/java/com/example/demo/global/exception/GlobalExceptionHandler.java
  backend/src/test/java/com/example/demo/global/auth/kakao/KaKaoUserInfoResponseTest.java
Labels: 백엔드, 사용자 정보

#56 feat: #39 #40 #41 #53 도메인 Entity제거 및 테스트 코드 작성
  backend/build.gradle
  backend/src/main/java/com/example/demo/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/example/demo/domain/chat/entity/ChatRoomUser.java
  backend/src/main/java/com/example/demo/domain/chat/service/ChatMessageService.java
  backend/src/main/java/com/example/demo/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/example/demo/domain/user/controller/UserJoinController.java
  backend/src/main/java/com/example/demo/domain/user/controller/UserLoginController.java
  backend/src/main/java/com/example/demo/domain/user/controller/UserRecoveryController.java
  backend/src/main/java/com/example/demo/domain/user/dto/command/CheckEmailCommand.java
  backend/src/main/java/com/example/demo/domain/user/dto/command/CheckEmailVerificationCommand.java
  backend/src/main/java/com/example/demo/domain/user/dto/command/SendEmailVerificationCommand.java
  backend/src/main/java/com/example/demo/domain/user/dto/command/UserJoinCheckCommand.java
  backend/src/main/java/com/example/demo/domain/user/dto/command/UserJoinCommand.java
  backend/src/main/java/com/example/demo/domain/user/dto/command/UserLoginCommand.java
  backend/src/main/java/com/example/demo/domain/user/entity/PendingEmail.java
  backend/src/main/java/com/example/demo/domain/user/entity/User.java
  backend/src/main/java/com/example/demo/domain/user/mapper/EmailMapper.java
  backend/src/main/java/com/example/demo/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/example/demo/domain/user/model/PendingEmail.java
  backend/src/main/java/com/example/demo/domain/user/model/User.java
  backend/src/main/java/com/example/demo/domain/user/repository/PendingEmailsRepository.java
  backend/src/main/java/com/example/demo/domain/user/repository/UserRepository.java
  backend/src/main/java/com/example/demo/domain/user/service/EmailService.java
  backend/src/main/java/com/example/demo/domain/user/service/UserService.java
  backend/src/main/java/com/example/demo/domain/util/BaseResponse.java
  backend/src/main/java/com/example/demo/domain/util/FailResponse.java
  backend/src/main/java/com/example/demo/global/auth/OAuth2FailureHandler.java
  backend/src/main/java/com/example/demo/global/auth/PrincipalDetails.java
  backend/src/main/java/com/example/demo/global/auth/jwt/JwtTokenDTO.java
  backend/src/main/java/com/example/demo/global/auth/jwt/JwtTokenProvider.java
  backend/src/main/java/com/example/demo/global/auth/kakao/KaKaoOAuth2Controller.java
  backend/src/main/java/com/example/demo/global/auth/kakao/KakaoOAuth2Service.java
  backend/src/main/java/com/example/demo/global/auth/oauth/OAuth2UserService.java
  backend/src/main/java/com/example/demo/global/exception/GlobalExceptionHandler.java
  backend/src/test/java/com/example/demo/domain/user/controller/UserJoinControllerTest.java
  backend/src/test/java/com/example/demo/domain/user/controller/UserLoginControllerTest.java
  backend/src/test/java/com/example/demo/domain/user/controller/UserRecoveryControllerTest.java
  backend/src/test/java/com/example/demo/domain/user/dto/command/CheckEmailCommandTest.java
  backend/src/test/java/com/example/demo/domain/user/dto/command/CheckEmailVerificationCommandTest.java
  backend/src/test/java/com/example/demo/domain/user/dto/command/SendEmailVerificationCommandTest.java
  backend/src/test/java/com/example/demo/domain/user/dto/command/UserJoinCheckCommandTest.java
  backend/src/test/java/com/example/demo/domain/user/dto/command/UserJoinCommandTest.java
  backend/src/test/java/com/example/demo/domain/user/dto/command/UserLoginCommandTest.java
  backend/src/test/resources/emails.csv
  backend/src/test/resources/invalid-emails.csv
  backend/src/test/resources/name.csv
Labels: 백엔드, 리펙토링, 테스트

#68 feat : #51 ChatRoom, ChatMessage Swagger API
  backend/src/main/java/com/example/demo/domain/chat/controller/ChatController.java
  backend/src/main/java/com/example/demo/domain/chat/controller/ChatMessageController.java
  backend/src/main/java/com/example/demo/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/example/demo/domain/chat/dto/ChatMessageCreateRequest.java
  backend/src/main/java/com/example/demo/domain/chat/dto/ChatMessageDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/ChatMessageReadCondition.java
  backend/src/main/java/com/example/demo/domain/chat/dto/ChatRoomCreateRequest.java
  backend/src/main/java/com/example/demo/domain/chat/dto/ChatRoomDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/ChatRoomResponse.java
  backend/src/main/java/com/example/demo/domain/chat/dto/SimpleChatRoomDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/request/ChatMessageCreateRequest.java
  backend/src/main/java/com/example/demo/domain/chat/dto/request/ChatMessageReadCondition.java
  backend/src/main/java/com/example/demo/domain/chat/dto/request/ChatRoomCreateRequest.java
  backend/src/main/java/com/example/demo/domain/chat/dto/request/ChatRoomDeleteRequest.java
  backend/src/main/java/com/example/demo/domain/chat/dto/response/ChatMessageDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/response/ChatMessageReadResponseDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/response/ChatRoomCreateResponseDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/response/ChatRoomDeleteResponseDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/response/ChatRoomDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/response/ChatRoomListResponseDto.java
  backend/src/main/java/com/example/demo/domain/chat/dto/response/SimpleChatRoomResponseDto.java
  backend/src/main/java/com/example/demo/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/example/demo/domain/chat/repository/ChatMessageJpaRepository.java
  backend/src/main/java/com/example/demo/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/example/demo/domain/chat/repository/ChatRoomJpaRepository.java
  backend/src/main/java/com/example/demo/domain/chat/repository/ChatRoomUserJpaRepository.java
  backend/src/main/java/com/example/demo/domain/chat/service/ChatMessageService.java
  backend/src/main/java/com/example/demo/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/example/demo/domain/chat/service/RedisPublisher.java
  backend/src/main/java/com/example/demo/domain/chat/service/RedisSubscriber.java
  backend/src/main/java/com/example/demo/global/exception/ExceptionCode.java
Labels: 백엔드

#74 feat: #67 이메일 로그인 기능 구현
  frontend/api/login.ts
  frontend/api/users.ts
  frontend/app/(auth)/(routes)/login/page.tsx
  frontend/app/(auth)/components/login/LoginForm/LoginForm.tsx
  frontend/app/(auth)/constants/login/schema.ts
  frontend/app/(auth)/hooks/login/useLogin.tsx
  frontend/app/(auth)/types/login.ts
  frontend/app/(mypage)/(routes)/mypage/page.tsx
  frontend/app/layout.tsx
  frontend/components.json
  frontend/components/header/Header.tsx
  frontend/components/header/NavLinks.tsx
  frontend/components/navigation/NavLinks.tsx
  frontend/components/providers/AuthProvider.tsx
  frontend/components/providers/QueryProvider.tsx
  frontend/components/providers/ToastProvider.tsx
  frontend/components/ui/button/button.tsx
  frontend/components/ui/checkbox/checkbox.tsx
  frontend/components/ui/form/form.tsx
  frontend/components/ui/input/input.tsx
  frontend/components/ui/label/label.tsx
  frontend/components/ui/radio-group/radio-group.tsx
  frontend/components/ui/select/select.tsx
  frontend/constants/localstorage.ts
  frontend/constants/queryKeys.ts
  frontend/hooks/user/useProfile.ts
  frontend/lib/axios/instance.ts
  frontend/lib/cn.ts
  frontend/lib/localstorage.ts
  frontend/lib/parseJwt.ts
  frontend/lib/query/generateKeys.ts
  frontend/types/user.ts
Labels: 새로운 기능, 프론트
